### ISSUE TITLE
Potential security vulnerability

### ISSUE THREAD

**Issue by kamal-groww** [Groww/grafana-rbac-controller#6]
Can new users created this way login with email / password ?  If yes then wouldn't it be possible to login as any user if the email id is known ?
https://github.com/Groww/grafana-rbac-controller/blob/6068b472aae1de8e9f27561bcd334a55ac42ffc5/grafana.go#L36

**Comment by abhayverma-groww** [comment]
Login with email/password isn't supported on custom OAuth2-proxy login screen and it supports only google authentication.
Since this could be a potential security issue, we will generate random password for each new user on signup to fix this.
Thanks for highlighting.
